stages:
  prepare:
    cmd: python -m src.features.prepare
    deps:
    - data/raw/raw_data.csv
    - src/features/prepare.py
    params:
    - prepare.random_state
    - prepare.test_size
    - prepare.train_size
    outs:
    - data/processed/test/test_data_processed.csv
    - data/processed/train/train_data_processed.csv
  extract_data:
    cmd: python -m src/features/extract
    deps:
    - src/features/extract.py
    outs:
    - data/raw/raw_data.csv
