stages:
  extract_data:
    cmd: python -m src.features.extract
    deps:
      - src/features/extract.py
    outs:
      - data/raw
  prepare:
    cmd: python -m src.features.prepare
    deps:
    - data/raw/raw_data.csv
    - src/features/prepare.py
    params:
    - prepare.random_state
    - prepare.test_size
    - prepare.train_size
    outs:
    - data/processed/test
    - data/processed/train
  train:
    cmd: python -m src.models.train_model
    deps:
    - data/processed/train/train_data.csv
    - src/models/train_model.py
    outs:
    - models/transfer-learning.joblib
  test:
    cmd: python -m src.models.test_model
    deps:
    - data/processed/test/test_data.csv
    - models/dvclive/transfer-learning.joblib
    - src/models/test_model.py
    metrics:
    - metrics/scores.json:
        cache: false
