stages:
  prepare:
    cmd: python -m src.features.prepare
    deps:
      - kaggle.json
      - src/features/prepare.py
    params:
      - prepare
    outs:
      - data/raw/
      - data/processed/
  train:
    cmd: python -m src.models.train_model
    deps:
      - data/processed/
      - src/models/train_model.py
    params:
      - train
    outs:
      - models/
  test:
    cmd: python -m src.models.test_model
    deps:
      - data/processed/
      - models
      - src/models/test_model.py
    params:
      - test